### ISSUE TITLE
Categories mismatch

### ISSUE THREAD

**Issue by japhb** [perl6/perl6-examples#21]
The categories listed on the home page of examples.perl6.org don't match the category tabs across the topnav.  There are some naming inconsistencies, but more importantly there are tabs with no associated description in the category list.

**Comment by paultcochrane** [comment]
Thanks for spotting this!  The missing categories in the category list have been added.  Also, the way the tabs are created has been improved/made more flexible (as of 66425da14867ea660686e09a1d4ad7cbdfa44203).  Have a look at the site again and let me know if these changes have addressed the naming inconsistency issue.
