### ISSUE TITLE
solution to project euler problem 99 does not compile

### ISSUE THREAD

**Issue by nagarajasr** [perl6/perl6-examples#25]
solution to project euler problem 99 does not compile

```code
$ perl6 --version
This is perl6 version 2015.06 built on MoarVM version 2015.06

perl6 prob099-andreoss.pl
Dynamic variable $*PROGRAM-NAME not found
  in sub MAIN at prob099-andreoss.pl:45
  in block <unit> at prob099-andreoss.pl:45
```

**Comment by vendethiel** [comment]
upgrade your perl6 :-).

**Comment by coke** [comment]
Verified, this works with a version of rakudo built from HEAD. Will be covered by the next monthly release; sorry about the breakage; Trying to get any breaking changes in before the official release this year.

**Comment by nagarajasr** [comment]
thank you.
