### ISSUE TITLE
Source code won't display for some snippets

### ISSUE THREAD

**Issue by vendethiel** [perl6/perl6-examples#31]
Example here: http://examples.perl6.org/categories/best-of-rosettacode/accumulator-factory.html

Most of the examples seem to work fine, though.

**Comment by zoffixznet** [comment]
Looking at source code of those, seems to be a problem with handling intertwined POD

**Comment by stmuk** [comment]
I cheated and removed the 2nd POD section since it wasn't useful anyway!
