### ISSUE TITLE
games/wizard.pl crash

### ISSUE THREAD

**Issue by BlueT** [perl6/perl6-examples#33]
matthew@0xB1uE7:~/tmp$ perl6 -v
This is perl6 version 2015.09-383-gf0d4820 built on MoarVM version 2015.09-79-gee9fc2b

matthew@0xB1uE7:~/tmp$ perl6 ./wizard.pl 
What is your name: BT
Greetings, BT
BTiscurrently in theLobby

18
Army of frogs is attacking you! What will you do?
Use of uninitialized value $choice of type Any in string context
Any of .^name, .perl, .gist, or .say can stringify undefined things, if needed.  in method battle at ./wizard.pl:117
Type check failed in assignment to $!param; expected Str but got Weapon
  in block  at ./wizard.pl:120
  in method battle at ./wizard.pl:117
  in block <unit> at ./wizard.pl:217

**Comment by moritz** [comment]
I've fixed some stuff that broke in the last 7 years or so since this example was added, but there's still a lot that isn't working, and likely never did.

If nobody steps up to fix it, I'll remove this example.

**Comment by paultcochrane** [comment]
+1 to removing.  IIRC, I managed to get the example compiling, but it never
actually worked properly.
