### ISSUE TITLE
https

### ISSUE THREAD

**Issue by hankache** [perl6/perl6-examples#48]
Fix https for examples.perl6.org  
It works everywhere else.

**Comment by JJ** [comment]
Well noted, but I am not sure that bug report should go here... Not sure
where else, either.

**Comment by moritz** [comment]
I've fixed the SSL.

For the record, I changed `/root/letsencrypt/more-certs.sh` on www.p6c.org to generate a certificate for this subdomain, added a virtual host for Apache, and restarted Apache.
