### ISSUE TITLE
Travis is failing

### ISSUE THREAD

**Issue by JJ** [perl6/perl6-examples#53]
And it seems to be [simply due to the use of `pack`](https://travis-ci.org/perl6/perl6-examples). Should be easy to solve.

**Comment by paultcochrane** [comment]
Actually, the problem seems to be due to the `FastCGI` dependency:

```
===> Install [FAIL] for FastCGI:ver<0.9.0>: ===SORRY!=== Error while compiling /home/travis/build/perl6/perl6-examples/site#sources/D33B2CF81EB010BB6A219D2AF5F873163A6DBF44 (FastCGI::Protocol)
Use of pack is experimental; please 'use experimental :pack'
at /home/travis/build/perl6/perl6-examples/site#sources/D33B2CF81EB010BB6A219D2AF5F873163A6DBF44 (FastCGI::Protocol):447
------> <BOL>⏏<EOL>
    expecting any of:
        postfix
        statement end
===SORRY!=== Error while compiling /home/travis/build/perl6/perl6-examples/site#sources/D33B2CF81EB010BB6A219D2AF5F873163A6DBF44 (FastCGI::Protocol)
Use of pack is experimental; please 'use experimental :pack'
at /home/travis/build/perl6/perl6-examples/site#sources/D33B2CF81EB010BB6A219D2AF5F873163A6DBF44 (FastCGI::Protocol):447
------> <BOL>⏏<EOL>
    expecting any of:
        postfix
        statement end
make: *** [install-deps] Error 1
```

A `git grep` in the `perl6-examples` code doesn't show up any use of `pack`, so my guess is that the problem is really upstream.

**Comment by JJ** [comment]
Right... And it remains to be seen whether FastCGI is actually used, too...

**Comment by paultcochrane** [comment]
Hrm, [hope is not a strategy](https://landing.google.com/sre/sre-book/chapters/introduction/) :-/  For some reason FastCGI is still found as a dependency on Travis.  The odd thing is that I can't reproduce this in my environment (Debian stretch; moar, nqp, rakudo, zef built and installed from source), which I *think* should be sufficently similar to the environment on Travis.

**Comment by paultcochrane** [comment]
It looks like bug I mentioned above has been fixed in a recent Rakudo commit.  Unfortunately, the Travis tests are still failing sometimes due to a flappy test in the perl6-examples code...

**Comment by JJ** [comment]
Thanks, Paul, for taking care of this...

**Comment by dwarring** [comment]
Bumped to Rakudo 2018.05 for Pod::To::HTML and friends (2b9742a ). Also fixed a 50/50 chance of 070-categories.t failing due to unstable ordering in Categories.categories-list (bb38add).

**Comment by paultcochrane** [comment]
@dwarring Thanks for getting the tests passing again!  Do you know what was causing the error when installing Pod::To::HTML?  I hadn't yet managed to work out what 

```
No such method 'new-without-check' for invocant of type 'CompUnit::PrecompilationId'
```

meant.

**Comment by JJ** [comment]
Pod::To::HTML needs a minimum 2018.11 version, actually, since it's using the latest additions to the Pod parsing code...

**Comment by paultcochrane** [comment]
Interesting... Should Pod::To::HTML perhaps specify `6.d` as the version as the Perl version requirement in its metadata?  That way dependent packages can use the correct version requirements.  Just a thought...

**Comment by JJ** [comment]
2018.11 is not 6.d yet, I think, but I guess specifying a minimum version is a must anyway.

**Comment by dwarring** [comment]
Fwiw, Pod::To::HTML is used by htmlify.pl to generate HTML. Does at least run to completion on Rakudo 2018.05, after installing the latest Pod::To::HTML.

**Comment by paultcochrane** [comment]
@JJ Travis is back green again.  Are you happy that this issue is resolved?

**Comment by JJ** [comment]
Totally! Great work!
