### ISSUE TITLE
[Question] Is a maintainer needed?

### ISSUE THREAD

**Issue by Altai-man** [perl6/perl6-examples#66]
I think it is not a secret that this repo is outdated, not only that, it lacks a maintainer to take care of broken examples, blatantly old-style perl 6 code (it's ok when we demonstrate various approaches to users, but tooling is very this way too, and it is broken right now).

Anyone is against me working on reviving this project? Saving it for historical reasons or something like this? In case nobody argues against that in 7 days, I'll start tinker on things (in ways I see reasonable from my point of view, of course).

**Comment by JJ** [comment]
Please do that. Document everything you do via issues. Also, you might want to migrate the repo to the Raku org first.
